"""empty message

Revision ID: 0a9fa3d6457b
Revises: ba384193f818
Create Date: 2019-03-25 08:49:04.926697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a9fa3d6457b'
down_revision = 'ba384193f818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('top_prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('dataset', sa.String(length=64), nullable=True),
    sa.Column('predicted_out', sa.Float(), nullable=True),
    sa.Column('num_subs', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('top_prediction')
    # ### end Alembic commands ###
