"""empty message

Revision ID: 0fe614d37b97
Revises: 6ab1e4c5d331
Create Date: 2019-03-21 08:47:36.206697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe614d37b97'
down_revision = '6ab1e4c5d331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_stat', sa.Column('upload_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ml_stat', 'upload_date')
    # ### end Alembic commands ###
