"""add relationship

Revision ID: 14d4fb382376
Revises: 4766fccaf084
Create Date: 2019-03-14 14:16:43.301533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14d4fb382376'
down_revision = '4766fccaf084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction', sa.Column('sub_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'prediction', 'submission', ['sub_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prediction', type_='foreignkey')
    op.drop_column('prediction', 'sub_id')
    # ### end Alembic commands ###
