"""empty message

Revision ID: 203842e47def
Revises: 18f471784fc4
Create Date: 2019-04-05 12:49:33.198140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203842e47def'
down_revision = '18f471784fc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crank', sa.Column('upload_filename', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crank', 'upload_filename')
    # ### end Alembic commands ###
