"""empty message

Revision ID: 3d4e37e726eb
Revises: b383ba867552
Create Date: 2019-03-20 17:12:34.110792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d4e37e726eb'
down_revision = 'b383ba867552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crank', sa.String(length=64), nullable=True),
    sa.Column('upload_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('science_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crank', sa.String(length=64), nullable=True),
    sa.Column('upload_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('science_stat')
    op.drop_table('ml_stat')
    # ### end Alembic commands ###
