"""empty message

Revision ID: 4658f6697b50
Revises: 1076d5169c91
Create Date: 2019-07-24 17:41:31.999866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4658f6697b50'
down_revision = '1076d5169c91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crank', sa.Column('num_training_rows', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crank', 'num_training_rows')
    # ### end Alembic commands ###
