"""empty message

Revision ID: 6ab1e4c5d331
Revises: 3d4e37e726eb
Create Date: 2019-03-21 07:37:18.913076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ab1e4c5d331'
down_revision = '3d4e37e726eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ml_stat', 'upload_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_stat', sa.Column('upload_date', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
