"""empty message

Revision ID: 847397a69692
Revises: ed8065751152
Create Date: 2019-03-31 20:54:37.655109

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '847397a69692'
down_revision = 'ed8065751152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('science_stat', sa.Column('amine', sa.String(length=256), nullable=True))
    op.add_column('science_stat', sa.Column('success', sa.Integer(), nullable=True))
    op.add_column('science_stat', sa.Column('total', sa.Integer(), nullable=True))
    op.drop_column('science_stat', 'upload_date')
    op.drop_column('science_stat', 'crank')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('science_stat', sa.Column('crank', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('science_stat', sa.Column('upload_date', mysql.DATETIME(), nullable=True))
    op.drop_column('science_stat', 'total')
    op.drop_column('science_stat', 'success')
    op.drop_column('science_stat', 'amine')
    # ### end Alembic commands ###
