"""empty message

Revision ID: 85b792a0077c
Revises: 95eb6d0048fa
Create Date: 2019-03-25 15:49:40.081890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85b792a0077c'
down_revision = '95eb6d0048fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crank', 'stateset')
    op.add_column('leader_board', sa.Column('githash', sa.String(length=64), nullable=True))
    op.drop_column('leader_board', 'gitcommit')
    op.add_column('run', sa.Column('githash', sa.String(length=7), nullable=True))
    op.drop_column('run', 'crank')
    op.drop_column('run', 'stateset')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('stateset', mysql.VARCHAR(length=11), nullable=True))
    op.add_column('run', sa.Column('crank', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('run', 'githash')
    op.add_column('leader_board', sa.Column('gitcommit', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('leader_board', 'githash')
    op.add_column('crank', sa.Column('stateset', mysql.VARCHAR(length=11), nullable=True))
    # ### end Alembic commands ###
