"""empty message

Revision ID: 95eb6d0048fa
Revises: b287ea062f2a
Create Date: 2019-03-25 14:04:28.531817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95eb6d0048fa'
down_revision = 'b287ea062f2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leader_board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(length=64), nullable=True),
    sa.Column('gitcommit', sa.String(length=64), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('model_author', sa.String(length=64), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('balanced_accuracy', sa.Float(), nullable=True),
    sa.Column('auc_score', sa.Float(), nullable=True),
    sa.Column('average_precision', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('samples_in_train', sa.Integer(), nullable=True),
    sa.Column('samples_in_test', sa.Integer(), nullable=True),
    sa.Column('model_description', sa.Text(), nullable=True),
    sa.Column('column_predicted', sa.String(length=64), nullable=True),
    sa.Column('num_features_used', sa.Integer(), nullable=True),
    sa.Column('data_and_split_description', sa.Text(), nullable=True),
    sa.Column('normalized', sa.Boolean(), nullable=True),
    sa.Column('num_features_normalized', sa.Integer(), nullable=True),
    sa.Column('feature_extraction', sa.Boolean(), nullable=True),
    sa.Column('was_untested_data_predicted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leader_board')
    # ### end Alembic commands ###
