"""empty message

Revision ID: 9c54afc39689
Revises: 203842e47def
Create Date: 2019-04-08 20:31:03.374328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c54afc39689'
down_revision = '203842e47def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crank', sa.Column('train_filename', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crank', 'train_filename')
    # ### end Alembic commands ###
