"""empty message

Revision ID: adbf897e28b5
Revises: e072fdfc4fee
Create Date: 2019-03-30 19:01:36.621291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adbf897e28b5'
down_revision = 'e072fdfc4fee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chemical',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('inchi', sa.String(length=512), nullable=True),
    sa.Column('common_name', sa.String(length=512), nullable=True),
    sa.Column('abbrev', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chemical')
    # ### end Alembic commands ###
