"""empty message

Revision ID: b383ba867552
Revises: e28fa442b4f3
Create Date: 2019-03-20 16:17:25.445433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b383ba867552'
down_revision = 'e28fa442b4f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crank', sa.String(length=64), nullable=True),
    sa.Column('upload_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('num_runs', sa.Integer(), nullable=True),
    sa.Column('num_uploads', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('automation_stat')
    # ### end Alembic commands ###
