"""empty message

Revision ID: ba384193f818
Revises: 0fe614d37b97
Create Date: 2019-03-25 08:16:00.828900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba384193f818'
down_revision = '0fe614d37b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automation_stat', sa.Column('num_distinct', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('automation_stat', 'num_distinct')
    # ### end Alembic commands ###
