"""empty message

Revision ID: bc2693a937af
Revises: 0b4ee4b91350
Create Date: 2019-04-12 18:26:06.320017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc2693a937af'
down_revision = '0b4ee4b91350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_importance_value', sa.Column('entry_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'feature_importance_value', 'feature_importance', ['entry_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feature_importance_value', type_='foreignkey')
    op.drop_column('feature_importance_value', 'entry_id')
    # ### end Alembic commands ###
