"""empty message

Revision ID: d18508fd00d3
Revises: 
Create Date: 2019-03-18 12:49:15.635764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd18508fd00d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crank', sa.String(length=64), nullable=True),
    sa.Column('stateset', sa.String(length=11), nullable=True),
    sa.Column('githash', sa.String(length=7), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('num_runs', sa.Integer(), nullable=True),
    sa.Column('current', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crank', sa.String(length=64), nullable=True),
    sa.Column('stateset', sa.String(length=11), nullable=True),
    sa.Column('dataset', sa.String(length=11), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('_rxn_M_inorganic', sa.Float(), nullable=True),
    sa.Column('_rxn_M_organic', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('expname', sa.String(length=64), nullable=True),
    sa.Column('crank', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('dataset', sa.String(length=64), nullable=True),
    sa.Column('predicted_out', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['sub_id'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction')
    op.drop_table('submission')
    op.drop_table('run')
    op.drop_table('crank')
    # ### end Alembic commands ###
