"""empty message

Revision ID: d19d0bd20b7b
Revises: c91d6e626bc2
Create Date: 2019-04-23 21:32:24.579366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd19d0bd20b7b'
down_revision = 'c91d6e626bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo_stat', 'inchi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo_stat', sa.Column('inchi', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
