"""empty message

Revision ID: e072fdfc4fee
Revises: f602738e3456
Create Date: 2019-03-25 19:42:35.044747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e072fdfc4fee'
down_revision = 'f602738e3456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crank', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_column('crank', 'current')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crank', sa.Column('current', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('crank', 'active')
    # ### end Alembic commands ###
