"""empty message

Revision ID: e18bf712444c
Revises: 85b792a0077c
Create Date: 2019-03-25 18:03:38.861092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e18bf712444c'
down_revision = '85b792a0077c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('githash', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'githash')
    # ### end Alembic commands ###
