"""empty message

Revision ID: ed8065751152
Revises: adbf897e28b5
Create Date: 2019-03-31 09:04:33.338585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed8065751152'
down_revision = 'adbf897e28b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_run', sa.Column('githash', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_run', 'githash')
    # ### end Alembic commands ###
