"""empty message

Revision ID: f9b1d64b021e
Revises: bc2693a937af
Create Date: 2019-04-13 21:09:05.234013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9b1d64b021e'
down_revision = 'bc2693a937af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('feature_importance', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feature_importance', 'created')
    op.drop_column('feature', 'created')
    # ### end Alembic commands ###
