# Copyright [2020] [Two Six Labs, LLC]
# Licensed under the Apache License, Version 2.0

APP_CONFIG_JSON = "app_config_json"
AVAILABLE_PAGES_DICT = "available_pages_dict"
CONFIG_FILE_FOLDER = "config_file_folder"
MAIN_CONFIG = "main_config.json"
BASIC_AUTH_USERNAME = "BASIC_AUTH_USERNAME"
BASIC_AUTH_PASSWORD = "BASIC_AUTH_PASSWORD"

# app config json keys
AVAILABLE_PAGES = "available_pages"
GRAPHICS = "graphics"
GRAPHIC_NUM = "graphic_{:d}"
POINTS_NUM = "points_{:d}"
SITE_TITLE = "title"
SITE_DESC = "brief_desc"
WEBPAGE_LABEL = "webpage_label"
LINK = "link"
GRAPHIC_TITLE = "title"
GRAPHIC_DESC = "brief_desc"
DATA_BACKEND = "data_backend"
POSTGRES = "psql"
PLOT_ID = "plot_id"
GRAPHIC_CONFIG_FILES = "graphic_config_files"
URL_ENDPOINT = "url_endpoint"
APP_DEPLOY_DATA = "app_deploy_data"
TEST_APP_DEPLOY_DATA = "test_app_deploy_data"
MAIN_DATA_SOURCE = "main_data_source"
ADDITIONAL_DATA_SOURCES = "additional_data_sources"
SQLALCHEMY_DATABASE_URI = "SQLALCHEMY_DATABASE_URI"
DEVELOPMENT = "development"

# Plotly constants
LAYOUT = "layout"
HEIGHT = "height"
AGGREGATE = "aggregate"
HOVER_DATA = "hover_data"
AGGREGATIONS = "aggregations"
TRANSFORMS = "transforms"
GROUPS = "groups"
PLOT_TYPE = "plot_type"
DATA_SOURCES = "data_sources"
DATA_UPLOAD_METADATA = "data_upload_metadata"
NEW_DATA_SOURCE = "new_data_source"
DATA_SOURCE_TYPE = "data_source_type"
JOIN_KEYS = "join_keys"
DATA_LOCATION = "filepath"
TABLE_COLUMN_SEPARATOR = ":"
DEFAULT_SELECTED = "default_selected"
CURRENT_PAGE = "current_page"
DATA = "data"
DATA_FILTERS = "data_filters"
PLOT_MANAGER = "plot_manager"
DATA_TO_PLOT_PATH = "data_to_plot_path"
PLOT_SPECIFIC_INFO = "plot_specific_info"
FILTERS = "filters"
DATABASE = "database"
SELECTABLE_DATA_DICT = "selectable_data_dict"
OPTION_TYPE = "type"
OPTION_COL = "column"
HOVERTEXT = "hovertext"
PAGE_NAME = "name"
X = "x"
Y = "y"
Z = "z"
ERROR_X = "error_x"
ERROR_Y = "error_y"
ERROR_Z = "error_z"

SCATTER = "scatter"
SCATTERGL = "scattergl"
BAR = "bar"
HEATMAP = "heatmap"
HEATMAPGL = "heatmapgl"
CONTOUR = "contour"
BOX = "box"
VIOLIN = "violin"
HISTOGRAM = "histogram"
HISTOGRAM2D = "histogram2d"
HISTOGRAM2DCONTOUR = "histogram2dcontour"
SCATTER3D = "scatter3d"
SURFACE = "surface"
MESH3D = "mesh3d"


# Available graphics keys
GRAPH_HTML_TEMPLATE = "graph_html_template"
OBJECT = "object"
SCHEMA_CLASS = "schema_class"

# Available selector keys
SELECT_HTML_TEMPLATE = "select_html_template"
COLUMN_NAME = "column"
ENTRIES = "entries"
TEXT = "text"
SELECT_OPTION = "options"
AXIS = "axis"
GROUPBY = "groupby"
GROUPBY_SELECTOR = "groupby_selector"
SELECTOR_TYPE = "type"
FILTER = "filter"
FILTERED_SELECTOR = "filtered_selector"
NUMERICAL_FILTER = "numerical_filter"
INEQUALITIES = "inequalities"
OPERATION = "operation"
VALUE = "value"
SELECTED = "selected"
INEQUALITY_LOC = "inequality_{}"
UPPER_INEQUALITY = "upper"
LOWER_INEQUALITY = "lower"
MAX = "max"
MIN = "min"
LIST_OF_VALUES = "list_of_values"
MULTIPLE = "multiple"
NO_GROUP_BY = "No Group By"
SELECTOR_NAME = "name"
VISIBLE = "visible"
DATETIME = "datetime"
# ALL of row
SHOW_ALL_ROW = "Show All Rows"

# JINJA CONSTANTS
JINJA_PLOT = "plots"
JINJA_BUTTONS = "buttons"
JINJA_GRAPH_HTML_FILE = "graph_html_file"
JINJA_SELECT_HTML_FILE = "select_html_file"
JINJA_SELECT_INFO = "select_info"
JINJA_PLOT_INFO = "plot_info"
ACTIVE_SELECTORS = "active_selector"


# DATA MANAGEMENT
INDEX_COLUMN = "row_index"
UPLOAD_ID = "upload_id"
UPLOAD_TIME = "upload_time"
UPLOAD_FILENAME = "upload_filename"
USERNAME = "username"
NOTES = "notes"
INACTIVE = "inactive"
ACTIVE = "active"
TABLE_NAME = "table_name"
DATA_SOURCE = "data_source"
CSVFILE = "csvfile"
DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S"

# addendum constants
ADDENDUM_DICT = "addendum_dict"
GRAPHIC_NAME = "graphic_name"
NUMERICAL_FILTER_NUM_LOC_TYPE = "numerical_filter_{:d}_{}_{}"
PROCESS = "process"

# setup constants
PAGE_ID = "page_id"
GRAPHIC = "graphic"
CONFIG_DICT = "config_dict"
GRAPHIC_STATUS = "graphic_status"
COPY = "copy"
OLD = "old"
NEW = "new"
COLLAPSE_DICT = "collapse_dict"

# schema constants, these come from json schema
ADDITIONAL_PROPERTIES = "additionalProperties"
PROPERTIES = "properties"
PATTERN_PROPERTIES = "patternProperties"
DESCRIPTION = "description"
TITLE = "title"
TYPE = "type"
ITEMS = "items"
PATTERN = "pattern"
REQUIRED = "required"
MIN_ITEMS = "minItems"
MAX_ITEMS = "maxItems"
OPTIONS = "options"
DEPENDENCIES = "dependencies"
DEFAULT = "default"
ENUM = "enum"
MINIMUM = "minimum"
MAXIMUM = "maximum"
ARRAY_STRING = "array"  # ARRAY collides with sqlalchemy class name
ONEOF = "oneOf"
STRING = "string"
NUMBER = "number"
INTEGER = "integer"
BOOLEAN = "boolean"

# schema constants, these come from https://github.com/json-editor/json-editor
HIDDEN = "hidden"
DISABLE_COLLAPSE = "disable_collapse"
COLLAPSED = "collapsed"
DISABLE_PROPERTIES = "disable_properties"
REMOVE_EMPTY_PROPERTIES = "remove_empty_properties"
DEFAULTPROPERTIES = "defaultProperties"

# schema constants
GRAPHIC_SCHEMA = "graphic_schema"
PLOT_MANAGER_SCHEMA = "plot_manager_schema"
VISUALIZATION_SCHEMA = "visualization_schema"
SELECTOR_SCHEMA = "selector_schema"
COLUMN_NAMES = "column_names"
VISUALIZATION = "visualization"
SELECTOR = "selector"
PLOTLY = "plotly"
SEABORN = "seaborn"
CYTOSCAPE = "cytoscape"
PLOT_MANAGERS = [PLOTLY, SEABORN, CYTOSCAPE]
GRAPHIC_META_INFO = "graphic_meta_info"
GRAPHIC_PATH = "graphic_path"

MAX_ENTRIES_FOR_FILTER_SELECTOR = 200

# JS schema constants
# need to match functions names in default_entries_dict in wizard_graphic_config_editor.html
COLUMN_VALUE_FILTER = "column_value_filter"
CALLBACK = "identity_callback"

# preview functionality
PREVIEW = "preview"

# Plotly API
ATTRIBUTES = "attributes"
LAYOUT_ATTRIBUTES = "layoutAttributes"

# Network constants
START = "start"
END = "end"
WEIGHTS = "weights"
DIRECTED = "directed"
LINE_PROPERTIES = "line propeties"
MARKER_PROPERTIES = "marker propeties"


# cytoscape
NODE_ID = "node_id"
GROUP = "group"
NODES = "nodes"
ID = "id"
EDGE_ID = "edge_id"
SOURCE = "source"
TARGET = "target"
EDGES = "edges"
ELEMENTS = "elements"
STYLE = "style"

ELEMENT_STYLE = "element_style"
ELEMENT_PROPERTIES = "element_properties"
PROPERTY_NAME = "property_name"
STYLE_NAME = "style_name"

# regex patterns
NO_DOTS = r"^[^\\.]*$"
ALPHA_NUMERIC_NO_SPACES = r"^[a-zA-Z0-9_]+$"
ONE_LETTER = r"^[a-zA-Z]$"
NON_EMPTY_STRING = r"[\s\S]+"
POSTGRES_TABLE_NAME_FORMAT_REGEX = r"^[a-zA-Z_]\w+$"

# seaborn
SEABORN_PLOT_BYTES = "seaborn_plot_bytes"
ASPECT_RATIO = "aspect_ratio"
FIGSIZE = "figsize"
